# backend/app/main.py
import logging
from fastapi import FastAPI
from fastapi.middleware.cors import CORSMiddleware

from app.database import Base, engine
from app.config import get_settings
from app.api import (
    auth, dashboard, agents, tasks, approvals, admin_orders,
    products, customers, cart, orders,
    support, leads,
)

settings = get_settings()
logger = logging.getLogger("urbanova")

# Auto-create all tables (requires every model to have been imported somewhere
# before this line runs — confirm app/models/__init__.py imports Cart, CartItem,
# AgentExecution, etc. alongside the rest, since SQLAlchemy only creates tables
# for models it has actually seen)
Base.metadata.create_all(bind=engine)

app = FastAPI(
    title="Urbanova API",
    description="Backend for Urbanova e-commerce & AI operations portal",
    version="1.0.0",
)

app.add_middleware(
    CORSMiddleware,
    allow_origins=["http://localhost:3000", "https://urbanova.vercel.app"],
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
    expose_headers=["X-Cart-Session"],
)


@app.on_event("startup")
async def warn_if_demo_mode():
    if settings.DEMO_MODE:
        logger.warning(
            "⚠️  DEMO_MODE is ON — AI responses are simulated in demo_service.py, "
            "NOT generated by n8n/Gemini. Set DEMO_MODE=false + configure N8N_*_WEBHOOK to go live."
        )


app.include_router(auth.router)
app.include_router(dashboard.router)
app.include_router(agents.router)
app.include_router(tasks.router)
app.include_router(approvals.router)
app.include_router(products.router)
app.include_router(customers.router)
app.include_router(cart.router)
app.include_router(orders.router)
app.include_router(admin_orders.router)
app.include_router(support.router)
app.include_router(leads.router)


@app.get("/api/health")
async def health():
    return {
        "status": "ok",
        "demo_mode": settings.DEMO_MODE,
        "n8n_connected": bool(settings.N8N_BASE_URL and not settings.DEMO_MODE),
    }